version: '3'

services:
  database:
    container_name: mydatabase
    image: mysql:latest
    ports:
      - "3306:3306"
    restart: "unless-stopped"
    environment:
      MYSQL_ROOT_PASSWORD: 12345aA@
      MYSQL_DATABASE: node
